#! /bin/sh

killall sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# audio
pipewire &
pipewire-pulse &
wireplumber &

# bluetooth
while true; do bluetoothctl connect 40:72:18:2D:73:46; sleep 5; done >/dev/null &

#video
xrandr --output DP-0 --mode 1920x1080 --rate 240

# mouse
xinput --set-prop 9 'libinput Accel Speed' -0.5

# wallpaper
feh --bg-scale /home/$USER/images/wallpapers/wallpaperpatterntemplate2.png

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc rule -a '*' state=floating
